#!/usr/bin/env bash
#
# Copyright (C) 2019 @alanndz (Telegram and Github)
# Copyright 2019 Kry9toN (Dhimas) 
# SPDX-License-Identifier: GPL-3.0-or-later
#
# <build> <clean> <cache>
#

ROM="komodo"
CDIR="$PWD/${ROM}"
LOG="${CDIR}/out/build-${ROM}.log"
BOT_API_KEY=""
CHAT_ID="-393505960"
cd $CDIR

#Fuction telegram

function send() {
  curl -F chat_id="$CHAT_ID" -F document=@"$LOG" https://api.telegram.org/bot$BOT_API_KEY/sendDocument
 }

export KOMODO_BUILD_TYPE=OFFICIAL
export KOMODO_OFFICIAL=true

#Main script
while true; do
	echo -e "\n[1] Build with cache"
	echo -e "[2] Clean"
	echo -e "[3] Quit"
	echo -ne "\n(i) Please enter a choice[1-3]: "
	
	read choice
	
	if [ "$choice" == "1" ]; then
	
	read -p "Enter your device : " DEVICE
	
	export CCACHE_DIR=./.ccache
	export USE_CCACHE=1
	export CCACHE_COMPRESS=1
	prebuilts/misc/linux-x86/ccache/ccache -M 50G
	
	. build/envsetup.sh
lunch "${ROM}"_"${DEVICE}"-userdebug
	
	
		mka bacon "${ROM}" 2>&1 | tee "${CDIR}/out/build-${ROM}.log"
		
		send
fi

if [ "$choice" == "2" ]; then
	make clean
	make clobber
fi

if [ "$choice" == "3" ]; then
		exit 
fi

done
echo -e "$nc"